package runner

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/jrswab/axe/internal/agent"
	"github.com/jrswab/axe/internal/artifact"
	"github.com/jrswab/axe/internal/budget"
	"github.com/jrswab/axe/internal/config"
	"github.com/jrswab/axe/internal/mcpclient"
	"github.com/jrswab/axe/internal/memory"
	"github.com/jrswab/axe/internal/provider"
	"github.com/jrswab/axe/internal/refusal"
	"github.com/jrswab/axe/internal/resolve"
	"github.com/jrswab/axe/internal/tool"
	"github.com/jrswab/axe/internal/xdg"
)

// defaultUserMessage is sent when no stdin content is piped.
const defaultUserMessage = "Execute the task described in your instructions."

// maxConversationTurns is the safety limit for the conversation loop.
const maxConversationTurns = 50

const maxToolOutputBytes = 1024

type toolExecResult struct {
	Result   provider.ToolResult
	Duration time.Duration
}

// Run executes an agent with the given options and returns the result.
func Run(ctx context.Context, opts Options) (*Result, error) {
	start := time.Now()

	stdout := opts.Stdout
	if stdout == nil {
		stdout = os.Stdout
	}
	stderr := opts.Stderr
	if stderr == nil {
		stderr = os.Stderr
	}

	// Step 1: Get current working directory for agent search
	cwd, err := os.Getwd()
	if err != nil {
		return nil, &ConfigError{Msg: "failed to get working directory", Err: err}
	}

	// Step 2: Load agent config
	searchDirs := agent.BuildSearchDirs("", cwd)
	if len(opts.AgentsDirs) > 0 {
		searchDirs = append(opts.AgentsDirs, searchDirs...)
	}
	cfg, err := agent.Load(opts.AgentName, searchDirs)
	if err != nil {
		return nil, &ConfigError{Msg: "failed to load agent", Err: err}
	}

	// Step 3: Apply overrides
	if opts.Model != "" {
		cfg.Model = opts.Model
	}
	if opts.Skill != "" {
		cfg.Skill = opts.Skill
	}

	// Step 4: Parse model
	provName, modelName, err := parseModel(cfg.Model)
	if err != nil {
		return nil, &ConfigError{Msg: "invalid model", Err: err}
	}

	// Step 5: Load global config
	globalCfg, err := config.Load()
	if err != nil {
		return nil, &ConfigError{Msg: "failed to load global config", Err: err}
	}

	// Step 6: Resolve working directory
	workdir, err := resolve.Workdir(opts.Workdir, cfg.Workdir)
	if err != nil {
		return nil, &ConfigError{Msg: "failed to resolve working directory", Err: err}
	}

	// Artifact directory lifecycle
	var artifactDir string
	var artifactIsAutoGenerated bool
	var artifactTracker *artifact.Tracker

	// Resolution order:
	// 1. --artifact-dir flag (if non-empty) → persistent
	// 2. TOML artifacts.dir (if non-empty and enabled) → persistent
	// 3. TOML artifacts.enabled = true with no dir → auto-generate
	// 4. None → inactive
	if !opts.DryRun {
		if opts.ArtifactDir != "" {
			expanded, expandErr := resolve.ExpandPath(opts.ArtifactDir)
			if expandErr != nil {
				return nil, &ConfigError{Msg: "failed to resolve --artifact-dir", Err: expandErr}
			}
			if !filepath.IsAbs(expanded) {
				expanded = filepath.Join(workdir, expanded)
			}
			artifactDir = expanded
		} else if cfg.Artifacts.Enabled && cfg.Artifacts.Dir != "" {
			expanded, expandErr := resolve.ExpandPath(cfg.Artifacts.Dir)
			if expandErr != nil {
				return nil, &ConfigError{Msg: "failed to resolve artifacts.dir", Err: expandErr}
			}
			if !filepath.IsAbs(expanded) {
				expanded = filepath.Join(workdir, expanded)
			}
			artifactDir = expanded
		} else if cfg.Artifacts.Enabled {
			// Auto-generate under XDG cache
			cacheDir, cacheErr := xdg.GetCacheDir()
			if cacheErr != nil {
				return nil, &ConfigError{Msg: "failed to get cache dir for artifacts", Err: cacheErr}
			}
			var randBytes [3]byte
			if _, randErr := rand.Read(randBytes[:]); randErr != nil {
				return nil, &RuntimeError{Msg: "failed to generate artifact run ID", Err: randErr}
			}
			runID := time.Now().Format("20060102T150405") + "-" + hex.EncodeToString(randBytes[:])
			artifactDir = filepath.Join(cacheDir, "artifacts", runID)
			artifactIsAutoGenerated = true
		}

		if artifactDir != "" {
			if mkErr := os.MkdirAll(artifactDir, 0o755); mkErr != nil {
				return nil, &RuntimeError{Msg: "failed to create artifact directory", Err: mkErr}
			}
			if setErr := os.Setenv("AXE_ARTIFACT_DIR", artifactDir); setErr != nil {
				return nil, &RuntimeError{Msg: "failed to set AXE_ARTIFACT_DIR", Err: setErr}
			}
			artifactTracker = artifact.NewTracker()
			defer func() { _ = os.Unsetenv("AXE_ARTIFACT_DIR") }()

			if artifactIsAutoGenerated {
				defer func() {
					if opts.KeepArtifacts {
						_, _ = fmt.Fprintf(stderr, "artifacts preserved: %s\n", artifactDir)
					} else {
						if removeErr := os.RemoveAll(artifactDir); removeErr != nil {
							_, _ = fmt.Fprintf(stderr, "Warning: failed to clean up artifact directory %q: %v\n", artifactDir, removeErr)
						}
					}
				}()
			}
		}
	}

	// Step 7: Resolve file globs
	files, err := resolve.Files(cfg.Files, workdir)
	if err != nil {
		return nil, &ConfigError{Msg: "failed to resolve files", Err: err}
	}

	// Step 8: Load skill
	configDir, err := xdg.GetConfigDir()
	if err != nil {
		return nil, &ConfigError{Msg: "failed to get config directory", Err: err}
	}
	skillContent, err := resolve.Skill(cfg.Skill, configDir)
	if err != nil {
		return nil, &ConfigError{Msg: "failed to load skill", Err: err}
	}

	// Step 9: Read stdin (only when not using pre-built messages)
	var stdinContent string
	var stdinErr error
	if len(opts.Messages) == 0 {
		if opts.Stdin != nil {
			data, readErr := io.ReadAll(opts.Stdin)
			if readErr != nil {
				stdinErr = fmt.Errorf("failed to read stdin: %w", readErr)
			} else {
				stdinContent = string(data)
			}
		} else {
			stdinContent, stdinErr = resolve.Stdin()
		}
		if stdinErr != nil {
			return nil, &RuntimeError{Msg: "failed to read stdin", Err: stdinErr}
		}
	}

	// Step 10: Build system prompt
	systemPrompt := resolve.BuildSystemPrompt(cfg.SystemPrompt, skillContent, files)

	// Step 10b: Memory — load entries into system prompt
	var memoryEntries string
	var memoryPath string
	var memoryCount int
	if cfg.Memory.Enabled {
		var memErr error
		memoryPath, memErr = memory.FilePath(opts.AgentName, cfg.Memory.Path)
		if memErr != nil {
			_, _ = fmt.Fprintf(stderr, "Warning: failed to load memory for %q: %v\n", opts.AgentName, memErr)
		} else {
			memoryEntries, memErr = memory.LoadEntries(memoryPath, cfg.Memory.LastN)
			if memErr != nil {
				_, _ = fmt.Fprintf(stderr, "Warning: failed to load memory for %q: %v\n", opts.AgentName, memErr)
			} else if memoryEntries != "" {
				systemPrompt += "\n\n---\n\n## Memory\n\n" + memoryEntries
			}

			memoryCount, memErr = memory.CountEntries(memoryPath)
			if memErr != nil {
				_, _ = fmt.Fprintf(stderr, "Warning: failed to load memory for %q: %v\n", opts.AgentName, memErr)
			} else if cfg.Memory.MaxEntries > 0 && memoryCount >= cfg.Memory.MaxEntries {
				_, _ = fmt.Fprintf(stderr, "Warning: agent %q memory has %d entries (max_entries: %d). Run 'axe gc %s' to trim.\n", opts.AgentName, memoryCount, cfg.Memory.MaxEntries, opts.AgentName)
			}
		}
	}

	// Step 11: Build user message (or use pre-built history)
	// Validate pre-built messages early before any provider setup.
	if len(opts.Messages) > 0 {
		if err := validateMessages(opts.Messages); err != nil {
			return nil, err
		}
	}

	var userMessage string
	if len(opts.Messages) > 0 {
		// skip Prompt/Stdin/default resolution
		userMessage = ""
	} else {
		userMessage = defaultUserMessage
		if strings.TrimSpace(opts.Prompt) != "" {
			userMessage = opts.Prompt
		} else if strings.TrimSpace(stdinContent) != "" {
			userMessage = stdinContent
		}
	}

	// Step 12: Resolve timeout
	timeout := 120
	if cfg.Timeout > 0 {
		timeout = cfg.Timeout
	}
	if opts.Timeout > 0 {
		timeout = opts.Timeout
	}

	// Pre-compute values needed for dry-run and execution
	effectiveMaxTokens := cfg.Budget.MaxTokens
	if opts.MaxTokens != nil {
		effectiveMaxTokens = *opts.MaxTokens
	}
	effectiveMaxDepth := 3
	if cfg.SubAgentsConf.MaxDepth > 0 && cfg.SubAgentsConf.MaxDepth <= 5 {
		effectiveMaxDepth = cfg.SubAgentsConf.MaxDepth
	}

	// Step 13: Dry-run
	if opts.DryRun {
		streamVal := opts.Stream || cfg.Stream
		paramsLine := fmt.Sprintf("temperature=%g, max_tokens=%d", cfg.Params.Temperature, cfg.Params.MaxTokens)
		if cfg.Params.ResponseFormat.IsSet() {
			paramsLine += fmt.Sprintf(", response_format=%s", cfg.Params.ResponseFormat.Type)
		}
		filePaths := make([]string, len(files))
		for i, f := range files {
			filePaths[i] = f.Path
		}
		parallel := true
		if cfg.SubAgentsConf.Parallel != nil {
			parallel = *cfg.SubAgentsConf.Parallel
		}
		mcpServers := make([]string, len(cfg.MCPServers))
		for i, s := range cfg.MCPServers {
			mcpServers[i] = fmt.Sprintf("%s: %s (%s)", s.Name, s.URL, s.Transport)
		}
		dryRunUserMessage := userMessage
		if len(opts.Messages) > 0 {
			dryRunUserMessage = "(pre-built message history)"
		}
		return &Result{
			Content: "",
			DryRun:  true,
			DryRunInfo: &DryRunInfo{
				Model:           fmt.Sprintf("%s/%s", provName, modelName),
				Workdir:         workdir,
				Timeout:         timeout,
				Params:          paramsLine,
				Budget:          effectiveMaxTokens,
				Stream:          streamVal,
				SystemPrompt:    systemPrompt,
				Skill:           skillContent,
				Files:           filePaths,
				UserMessage:     dryRunUserMessage,
				Memory:          memoryEntries,
				MemoryEnabled:   cfg.Memory.Enabled,
				Tools:           cfg.Tools,
				MCPServers:      mcpServers,
				SubAgents:       cfg.SubAgents,
				MaxDepth:        effectiveMaxDepth,
				Parallel:        parallel,
				SubAgentTimeout: cfg.SubAgentsConf.Timeout,
				MessageCount:    len(opts.Messages),
			},
			DurationMs: time.Since(start).Milliseconds(),
		}, nil
	}

	ctx, cancel := context.WithTimeout(ctx, time.Duration(timeout)*time.Second)
	defer cancel()

	// Step 14: Resolve API key and validate
	apiKey := globalCfg.ResolveAPIKey(provName)
	baseURL := globalCfg.ResolveBaseURL(provName)
	region := globalCfg.ResolveRegion(provName)

	if provName == "bedrock" {
		if region == "" {
			return nil, &ConfigError{Msg: fmt.Sprintf("region for provider %q is not configured (set AWS_REGION or add to config.toml)", provName)}
		}
		apiKey = region
		baseURL = ""
	}

	if provider.Supported(provName) && provName != "ollama" && provName != "bedrock" && apiKey == "" {
		envVar := config.APIKeyEnvVar(provName)
		return nil, &ConfigError{Msg: fmt.Sprintf("API key for provider %q is not configured (set %s or add to config.toml)", provName, envVar)}
	}

	// Step 15: Create provider
	var prov provider.Provider
	if provName == "openrouter" {
		prov, err = provider.NewOpenRouterProvider(apiKey, baseURL, globalCfg.ResolveReferer(provName), globalCfg.ResolveTitle(provName), globalCfg.ResolveCategories(provName))
	} else {
		prov, err = provider.New(provName, apiKey, baseURL)
	}
	if err != nil {
		return nil, &RuntimeError{Msg: "failed to create provider", Err: err}
	}

	// Step 15b: Wrap provider with retry decorator
	retryProv := provider.NewRetry(prov, provider.RetryConfig{
		MaxRetries:     cfg.Retry.MaxRetries,
		Backoff:        cfg.Retry.Backoff,
		InitialDelayMs: cfg.Retry.InitialDelayMs,
		MaxDelayMs:     cfg.Retry.MaxDelayMs,
		Verbose:        opts.Verbose,
		Stderr:         stderr,
	})
	prov = retryProv

	// Step 16: Build request
	var messages []provider.Message
	if len(opts.Messages) > 0 {
		messages = toProviderMessages(opts.Messages)
	} else {
		messages = []provider.Message{{Role: "user", Content: userMessage}}
	}

	req := &provider.Request{
		Model:       modelName,
		System:      systemPrompt,
		Messages:    messages,
		Temperature: cfg.Params.Temperature,
		MaxTokens:   cfg.Params.MaxTokens,
		CacheConfig: true,
	}

	if cfg.Params.ResponseFormat.IsSet() {
		req.ResponseFormat = provider.ResponseFormat{
			Type:   cfg.Params.ResponseFormat.Type,
			Schema: cfg.Params.ResponseFormat.Schema,
		}
	}

	tracker := budget.New(effectiveMaxTokens)

	// Step 17: Create tool registry and resolve configured tools
	registry := tool.NewRegistry()
	tool.RegisterAll(registry)

	if len(cfg.Tools) > 0 {
		resolvedTools, resolveErr := registry.Resolve(cfg.Tools)
		if resolveErr != nil {
			return nil, &ConfigError{Msg: "failed to resolve tools", Err: resolveErr}
		}
		req.Tools = append(req.Tools, resolvedTools...)
	}

	// Step 17b: Sub-agent depth and call_agent injection
	depth := 0
	if len(cfg.SubAgents) > 0 && depth < effectiveMaxDepth {
		req.Tools = append(req.Tools, tool.CallAgentTool(cfg.SubAgents))
	}

	var mcpRouter *mcpclient.Router
	if len(cfg.MCPServers) > 0 {
		mcpRouter = mcpclient.NewRouter()
		defer func() { _ = mcpRouter.Close() }()

		builtinNames := make(map[string]bool, len(req.Tools))
		for _, t := range req.Tools {
			builtinNames[t.Name] = true
		}

		for _, serverCfg := range cfg.MCPServers {
			if opts.Verbose {
				_, _ = fmt.Fprintf(stderr, "[mcp] Connecting to %q at %s (%s)\n", serverCfg.Name, serverCfg.URL, serverCfg.Transport)
			}
			client, connErr := mcpclient.Connect(ctx, serverCfg)
			if connErr != nil {
				if strings.Contains(connErr.Error(), "environment variable") || strings.Contains(connErr.Error(), "unsupported MCP transport") {
					return nil, &ConfigError{Msg: fmt.Sprintf("failed to connect MCP server %q", serverCfg.Name), Err: connErr}
				}
				return nil, &RuntimeError{Msg: fmt.Sprintf("failed to connect MCP server %q", serverCfg.Name), Err: connErr}
			}

			mcpTools, listErr := client.ListTools(ctx)
			if listErr != nil {
				_ = client.Close()
				return nil, &RuntimeError{Msg: fmt.Sprintf("failed to list tools from MCP server %q", serverCfg.Name), Err: listErr}
			}

			filtered, registerErr := mcpRouter.Register(client, mcpTools, builtinNames)
			if registerErr != nil {
				_ = client.Close()
				return nil, &ConfigError{Msg: fmt.Sprintf("failed to register MCP tools from %q", serverCfg.Name), Err: registerErr}
			}

			if opts.Verbose {
				_, _ = fmt.Fprintf(stderr, "[mcp] %q discovered %d tool(s), registered %d\n", serverCfg.Name, len(mcpTools), len(filtered))
				for _, discovered := range mcpTools {
					if builtinNames[discovered.Name] {
						_, _ = fmt.Fprintf(stderr, "[mcp] Skipping %q from %q (conflicts with built-in tool)\n", discovered.Name, serverCfg.Name)
					}
				}
			}

			req.Tools = append(req.Tools, filtered...)
		}
	}

	// Resolve whether streaming is actually usable.
	streamEnabled := opts.Stream || cfg.Stream
	if streamEnabled && !retryProv.SupportsStream() {
		streamEnabled = false
	}

	// Verbose: pre-call info
	if opts.Verbose {
		skillDisplay := cfg.Skill
		if skillDisplay == "" {
			skillDisplay = "(none)"
		}
		promptSource := "default"
		if len(opts.Messages) > 0 {
			promptSource = fmt.Sprintf("%d pre-built messages", len(opts.Messages))
		} else if strings.TrimSpace(opts.Prompt) != "" {
			promptSource = "flag"
		} else if strings.TrimSpace(stdinContent) != "" {
			promptSource = "stdin"
		}
		_, _ = fmt.Fprintf(stderr, "Model:    %s/%s\n", provName, modelName)
		_, _ = fmt.Fprintf(stderr, "Workdir:  %s\n", workdir)
		_, _ = fmt.Fprintf(stderr, "Skill:    %s\n", skillDisplay)
		_, _ = fmt.Fprintf(stderr, "Files:    %d file(s)\n", len(files))
		_, _ = fmt.Fprintf(stderr, "Prompt:   %s\n", promptSource)
		_, _ = fmt.Fprintf(stderr, "Timeout:  %ds\n", timeout)
		paramsLine := fmt.Sprintf("temperature=%g, max_tokens=%d", cfg.Params.Temperature, cfg.Params.MaxTokens)
		if cfg.Params.ResponseFormat.IsSet() {
			paramsLine += fmt.Sprintf(", response_format=%s", cfg.Params.ResponseFormat.Type)
		}
		_, _ = fmt.Fprintf(stderr, "Params:   %s\n", paramsLine)
		if cfg.Memory.Enabled {
			if memoryCount > 0 {
				_, _ = fmt.Fprintf(stderr, "Memory:   %d entries loaded from %s\n", memoryCount, memoryPath)
			} else {
				_, _ = fmt.Fprintf(stderr, "Memory:   0 entries (no memory file)\n")
			}
		}
	}

	// Step 18: Run execution
	var resp *provider.Response
	var totalInputTokens, totalOutputTokens, totalCacheReadTokens, totalCacheWriteTokens, totalToolCalls int
	var allToolCallDetails []ToolCallDetail
	var streamedText bool

	sendRequest := func() error {
		if streamEnabled {
			if sp, ok := prov.(provider.StreamProvider); ok {
				stream, streamErr := sp.SendStream(ctx, req)
				if streamErr != nil {
					return streamErr
				}
				var textWriter io.Writer
				if !opts.JSON && len(req.Tools) == 0 {
					textWriter = stdout
				}
				var drainErr error
				resp, drainErr = drainEventStream(stream, textWriter)
				if drainErr != nil {
					return drainErr
				}
				resp.Model = req.Model
				if !opts.JSON && len(req.Tools) == 0 {
					streamedText = true
				}
				return nil
			}
		}
		var sendErr error
		resp, sendErr = prov.Send(ctx, req)
		return sendErr
	}

	if len(req.Tools) == 0 {
		// Single-shot: no tools, no conversation loop
		if err = sendRequest(); err != nil {
			if opts.Verbose {
				_, _ = fmt.Fprintf(stderr, "Duration: %dms\n", time.Since(start).Milliseconds())
			}
			return nil, mapProviderError(err)
		}
		// Append assistant response to message history
		req.Messages = append(req.Messages, provider.Message{
			Role:    "assistant",
			Content: resp.Content,
		})
		totalInputTokens = resp.InputTokens
		totalOutputTokens = resp.OutputTokens
		totalCacheReadTokens = resp.CacheReadTokens
		totalCacheWriteTokens = resp.CacheWriteTokens
		tracker.Add(resp.InputTokens, resp.OutputTokens)

		if tracker.Exceeded() {
			_, _ = fmt.Fprintf(stderr, "budget exceeded: used %d of %d tokens\n", tracker.Used(), tracker.Max())
		}

		if opts.Verbose {
			_, _ = fmt.Fprintf(stderr, "Duration: %dms\n", time.Since(start).Milliseconds())
			if tracker.Max() > 0 {
				_, _ = fmt.Fprintf(stderr, "Tokens:   %d input, %d output (cumulative, budget: %d/%d)\n", resp.InputTokens, resp.OutputTokens, tracker.Used(), tracker.Max())
			} else {
				_, _ = fmt.Fprintf(stderr, "Tokens:   %d input, %d output\n", resp.InputTokens, resp.OutputTokens)
			}
			_, _ = fmt.Fprintf(stderr, "Cache:    %d read, %d written\n", resp.CacheReadTokens, resp.CacheWriteTokens)
			_, _ = fmt.Fprintf(stderr, "Stop:     %s\n", resp.StopReason)
		}
	} else {
		// Conversation loop: handle tool calls
		budgetExceeded := false
		for turn := 0; turn < maxConversationTurns; turn++ {
			// Check budget before making LLM call
			if tracker.Exceeded() {
				budgetExceeded = true
				break
			}

			if opts.Verbose {
				pendingToolCalls := 0
				for _, m := range req.Messages {
					if m.Role == "tool" {
						pendingToolCalls += len(m.ToolResults)
					}
				}
				if streamEnabled {
					if _, ok := prov.(provider.StreamProvider); ok {
						_, _ = fmt.Fprintf(stderr, "[turn %d] Streaming request (%d messages)\n", turn+1, len(req.Messages))
					} else {
						_, _ = fmt.Fprintf(stderr, "[turn %d] Sending request (%d messages, %d tool calls pending)\n", turn+1, len(req.Messages), pendingToolCalls)
					}
				} else {
					_, _ = fmt.Fprintf(stderr, "[turn %d] Sending request (%d messages, %d tool calls pending)\n", turn+1, len(req.Messages), pendingToolCalls)
				}
			}

			if err = sendRequest(); err != nil {
				if opts.Verbose {
					_, _ = fmt.Fprintf(stderr, "Duration: %dms\n", time.Since(start).Milliseconds())
				}
				return nil, mapProviderError(err)
			}

			totalInputTokens += resp.InputTokens
			totalOutputTokens += resp.OutputTokens
			totalCacheReadTokens += resp.CacheReadTokens
			totalCacheWriteTokens += resp.CacheWriteTokens
			tracker.Add(resp.InputTokens, resp.OutputTokens)

			if opts.Verbose {
				label := "Received response"
				if streamEnabled {
					if _, ok := prov.(provider.StreamProvider); ok {
						label = "Stream complete"
					}
				}
				_, _ = fmt.Fprintf(stderr, "[turn %d] %s: %s (%d tool calls)\n", turn+1, label, resp.StopReason, len(resp.ToolCalls))
			}

			// Append assistant response to history before deciding if we continue
			req.Messages = append(req.Messages, provider.Message{
				Role:      "assistant",
				Content:   resp.Content,
				ToolCalls: resp.ToolCalls,
			})

			// No tool calls: conversation is done
			if len(resp.ToolCalls) == 0 {
				break
			}

			// Stop before executing tools if budget is exceeded
			if tracker.Exceeded() {
				budgetExceeded = true
				break
			}

			totalToolCalls += len(resp.ToolCalls)

			// Determine parallel execution setting
			parallel := true
			if cfg.SubAgentsConf.Parallel != nil {
				parallel = *cfg.SubAgentsConf.Parallel
			}

			// Execute tool calls
			results := executeToolCalls(ctx, resp.ToolCalls, cfg, globalCfg, registry, mcpRouter, depth, effectiveMaxDepth, parallel, opts.Verbose, stderr, workdir, tracker, opts.AgentsDirs, workdir, artifactDir, artifactTracker)

			if opts.JSON {
				for i, tc := range resp.ToolCalls {
					input := tc.Arguments
					if input == nil {
						input = map[string]string{}
					}
					allToolCallDetails = append(allToolCallDetails, ToolCallDetail{
						Name:       tc.Name,
						Input:      input,
						Output:     truncateOutput(results[i].Result.Content),
						IsError:    results[i].Result.IsError,
						Turn:       turn,
						DurationMs: results[i].Duration.Milliseconds(),
					})
				}
			}

			// Append tool result message
			toolResults := make([]provider.ToolResult, len(results))
			for i, r := range results {
				toolResults[i] = r.Result
			}
			toolMsg := provider.Message{
				Role:        "tool",
				ToolResults: toolResults,
			}
			req.Messages = append(req.Messages, toolMsg)
		}

		// Check if we exhausted turns
		if !budgetExceeded && resp != nil && len(resp.ToolCalls) > 0 {
			return nil, &RuntimeError{Msg: fmt.Sprintf("agent exceeded maximum conversation turns (%d)", maxConversationTurns)}
		}

		if tracker.Exceeded() {
			_, _ = fmt.Fprintf(stderr, "budget exceeded: used %d of %d tokens\n", tracker.Used(), tracker.Max())
		}

		if opts.Verbose {
			_, _ = fmt.Fprintf(stderr, "Duration: %dms\n", time.Since(start).Milliseconds())
			if tracker.Max() > 0 {
				_, _ = fmt.Fprintf(stderr, "Tokens:   %d input, %d output (cumulative, budget: %d/%d)\n", totalInputTokens, totalOutputTokens, tracker.Used(), tracker.Max())
			} else {
				_, _ = fmt.Fprintf(stderr, "Tokens:   %d input, %d output (cumulative)\n", totalInputTokens, totalOutputTokens)
			}
			_, _ = fmt.Fprintf(stderr, "Cache:    %d read, %d written\n", totalCacheReadTokens, totalCacheWriteTokens)
			_, _ = fmt.Fprintf(stderr, "Stop:     %s\n", resp.StopReason)
		}
	}

	durationMs := time.Since(start).Milliseconds()

	// Build result
	result := &Result{
		Content:          resp.Content,
		Model:            resp.Model,
		InputTokens:      totalInputTokens,
		OutputTokens:     totalOutputTokens,
		Cost:             resp.Cost,
		StopReason:       resp.StopReason,
		CacheStatus:      resp.CacheStatus,
		CacheReadTokens:  totalCacheReadTokens,
		CacheWriteTokens: totalCacheWriteTokens,
		ToolCalls:        totalToolCalls,
		ToolCallDetails:  allToolCallDetails,
		DurationMs:       durationMs,
		Refused:          refusal.Detect(resp.Content),
		RetryAttempts:    retryProv.Attempts(),
		Budget: BudgetState{
			Max:      tracker.Max(),
			Used:     tracker.Used(),
			Exceeded: tracker.Exceeded(),
		},
	}
	// Only populate Messages for callers who provided a pre-built history.
	if len(opts.Messages) > 0 {
		result.Messages = fromProviderMessages(req.Messages)
	}

	if artifactTracker != nil {
		entries := artifactTracker.Entries()
		result.Artifacts = make([]ArtifactInfo, len(entries))
		for i, e := range entries {
			result.Artifacts[i] = ArtifactInfo{
				Path:  e.Path,
				Agent: e.Agent,
				Size:  e.Size,
			}
		}
	}

	// JSON output or text
	if opts.JSON {
		if result.ToolCallDetails == nil {
			result.ToolCallDetails = make([]ToolCallDetail, 0)
		}
		data, err := json.Marshal(result)
		if err != nil {
			return nil, &RuntimeError{Msg: "failed to marshal JSON output", Err: err}
		}
		_, _ = fmt.Fprintln(stdout, string(data))
	} else if !streamedText {
		_, _ = io.WriteString(stdout, resp.Content)
	}

	// Return budget exceeded error before memory append
	if tracker.Exceeded() {
		return nil, &BudgetExceededError{Used: tracker.Used(), Max: tracker.Max()}
	}

	// Step 19: Append memory entry after successful response
	if cfg.Memory.Enabled {
		appendPath, appendErr := memory.FilePath(opts.AgentName, cfg.Memory.Path)
		if appendErr != nil {
			_, _ = fmt.Fprintf(stderr, "Warning: failed to save memory for %q: %v\n", opts.AgentName, appendErr)
		} else {
			taskText := userMessage
			if len(opts.Messages) > 0 {
				taskText = firstUserMessageContent(opts.Messages)
				if taskText == "" {
					taskText = "(pre-built message history with no user message)"
				}
			}
			if appendErr = memory.AppendEntry(appendPath, taskText, resp.Content); appendErr != nil {
				_, _ = fmt.Fprintf(stderr, "Warning: failed to save memory for %q: %v\n", opts.AgentName, appendErr)
			}
		}
	}

	return result, nil
}

// drainEventStream consumes all events from a stream and constructs a Response.
// If w is non-nil, text events are written to it incrementally.
func drainEventStream(stream *provider.EventStream, w io.Writer) (*provider.Response, error) {
	defer func() { _ = stream.Close() }()

	var content strings.Builder
	var toolCalls []provider.ToolCall
	var inputTokens, outputTokens int
	var cacheReadTokens, cacheWriteTokens int
	var cost float64
	var stopReason string
	var cacheStatus string

	type pendingCall struct {
		id   string
		name string
		args strings.Builder
	}
	pending := make(map[string]*pendingCall)

	for {
		ev, err := stream.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			return nil, err
		}

		switch ev.Type {
		case provider.StreamEventText:
			content.WriteString(ev.Text)
			if w != nil {
				_, _ = io.WriteString(w, ev.Text)
			}

		case provider.StreamEventToolStart:
			pc := &pendingCall{id: ev.ToolCallID, name: ev.ToolName}
			if ev.ToolInput != "" {
				pc.args.WriteString(ev.ToolInput)
			}
			pending[ev.ToolCallID] = pc

		case provider.StreamEventToolDelta:
			if pc, ok := pending[ev.ToolCallID]; ok {
				pc.args.WriteString(ev.ToolInput)
			}

		case provider.StreamEventToolEnd:
			if pc, ok := pending[ev.ToolCallID]; ok {
				args := make(map[string]string)
				raw := pc.args.String()
				if raw != "" {
					var parsed map[string]interface{}
					if jsonErr := json.Unmarshal([]byte(raw), &parsed); jsonErr == nil {
						for k, v := range parsed {
							args[k] = fmt.Sprintf("%v", v)
						}
					}
				}
				toolCalls = append(toolCalls, provider.ToolCall{
					ID:        pc.id,
					Name:      pc.name,
					Arguments: args,
				})
				delete(pending, ev.ToolCallID)
			}

		case provider.StreamEventDone:
			inputTokens = ev.InputTokens
			outputTokens = ev.OutputTokens
			cost = ev.Cost
			stopReason = ev.StopReason
			cacheStatus = ev.CacheStatus
			cacheReadTokens = ev.CacheReadTokens
			cacheWriteTokens = ev.CacheWriteTokens
		}
	}

	return &provider.Response{
		Content:          content.String(),
		ToolCalls:        toolCalls,
		InputTokens:      inputTokens,
		OutputTokens:     outputTokens,
		CacheReadTokens:  cacheReadTokens,
		CacheWriteTokens: cacheWriteTokens,
		Cost:             cost,
		StopReason:       stopReason,
		CacheStatus:      cacheStatus,
	}, nil
}

// executeToolCalls dispatches tool calls and returns results.
// When parallel is true and there are multiple calls, they run concurrently.
func executeToolCalls(ctx context.Context, toolCalls []provider.ToolCall, cfg *agent.AgentConfig, globalCfg *config.GlobalConfig, registry *tool.Registry, mcpRouter *mcpclient.Router, depth, maxDepth int, parallel, verbose bool, stderr io.Writer, workdir string, budgetTracker *budget.BudgetTracker, agentsDirs []string, agentsBase string, artifactDir string, artifactTracker *artifact.Tracker) []toolExecResult {
	results := make([]toolExecResult, len(toolCalls))

	agentsDir := ""
	if len(agentsDirs) > 0 {
		agentsDir = agentsDirs[0]
	}

	execOpts := tool.ExecuteOptions{
		AllowedAgents:        cfg.SubAgents,
		ParentModel:          cfg.Model,
		Depth:                depth,
		MaxDepth:             maxDepth,
		Timeout:              cfg.SubAgentsConf.Timeout,
		GlobalConfig:         globalCfg,
		MCPRouter:            mcpRouter,
		Verbose:              verbose,
		Stderr:               stderr,
		BudgetTracker:        budgetTracker,
		AgentsDir:            agentsDir,
		AgentsBase:           agentsBase,
		AllowedHosts:         cfg.AllowedHosts,
		ArtifactDir:          artifactDir,
		ArtifactTracker:      artifactTracker,
		DefaultArtifactWrite: cfg.Artifacts.DefaultWrite,
	}

	ec := tool.ExecContext{
		Workdir:              workdir,
		Stderr:               stderr,
		Verbose:              verbose,
		AllowedHosts:         cfg.AllowedHosts,
		ArtifactDir:          artifactDir,
		ArtifactTracker:      artifactTracker,
		DefaultArtifactWrite: cfg.Artifacts.DefaultWrite,
	}

	if len(toolCalls) == 1 || !parallel {
		for i, tc := range toolCalls {
			start := time.Now()
			var r provider.ToolResult
			if mcpRouter != nil && mcpRouter.Has(tc.Name) {
				r = dispatchMCPToolCall(ctx, tc, mcpRouter, verbose, stderr)
			} else if tc.Name == tool.CallAgentToolName {
				r = tool.ExecuteCallAgent(ctx, tc, execOpts)
			} else {
				result, dispatchErr := registry.Dispatch(ctx, tc, ec)
				if dispatchErr != nil {
					r = provider.ToolResult{CallID: tc.ID, Content: dispatchErr.Error(), IsError: true}
				} else {
					r = result
				}
			}
			results[i] = toolExecResult{Result: r, Duration: time.Since(start)}
		}
	} else {
		type indexedResult struct {
			index  int
			result toolExecResult
		}
		ch := make(chan indexedResult, len(toolCalls))
		for i, tc := range toolCalls {
			go func(idx int, call provider.ToolCall) {
				start := time.Now()
				var res provider.ToolResult
				if mcpRouter != nil && mcpRouter.Has(call.Name) {
					res = dispatchMCPToolCall(ctx, call, mcpRouter, verbose, stderr)
				} else if call.Name == tool.CallAgentToolName {
					res = tool.ExecuteCallAgent(ctx, call, execOpts)
				} else {
					result, dispatchErr := registry.Dispatch(ctx, call, ec)
					if dispatchErr != nil {
						res = provider.ToolResult{CallID: call.ID, Content: dispatchErr.Error(), IsError: true}
					} else {
						res = result
					}
				}
				ch <- indexedResult{index: idx, result: toolExecResult{Result: res, Duration: time.Since(start)}}
			}(i, tc)
		}
		for range toolCalls {
			ir := <-ch
			results[ir.index] = ir.result
		}
	}

	return results
}

func dispatchMCPToolCall(ctx context.Context, tc provider.ToolCall, mcpRouter *mcpclient.Router, verbose bool, stderr io.Writer) provider.ToolResult {
	if verbose && stderr != nil {
		if serverName, ok := mcpRouter.ServerName(tc.Name); ok {
			_, _ = fmt.Fprintf(stderr, "[mcp] Routing tool %q to server %q\n", tc.Name, serverName)
		}
	}
	result, err := mcpRouter.Dispatch(ctx, tc)
	if err != nil {
		return provider.ToolResult{CallID: tc.ID, Content: err.Error(), IsError: true}
	}
	return result
}

func truncateOutput(s string) string {
	if len(s) <= maxToolOutputBytes {
		return s
	}
	i := maxToolOutputBytes
	for i > 0 && !utf8.RuneStart(s[i]) {
		i--
	}
	return s[:i] + "... (truncated)"
}

func parseModel(model string) (providerName, modelName string, err error) {
	idx := strings.Index(model, "/")
	if idx < 0 {
		return "", "", fmt.Errorf("invalid model format %q: expected provider/model-name", model)
	}
	providerName = model[:idx]
	modelName = model[idx+1:]
	if providerName == "" {
		return "", "", fmt.Errorf("invalid model format %q: empty provider", model)
	}
	if modelName == "" {
		return "", "", fmt.Errorf("invalid model format %q: empty model name", model)
	}
	return providerName, modelName, nil
}

func mapProviderError(err error) error {
	var provErr *provider.ProviderError
	if AsProviderError(err, &provErr) {
		switch provErr.Category {
		case provider.ErrCategoryAuth:
			return &RuntimeError{Msg: "provider auth error: check credentials/token (" + provErr.Message + ")", Err: provErr}
		case provider.ErrCategoryRateLimit:
			return &RuntimeError{Msg: "provider rate limit error: backoff or increase quota (" + provErr.Message + ")", Err: provErr}
		case provider.ErrCategoryTimeout, provider.ErrCategoryOverloaded, provider.ErrCategoryServer:
			return &RuntimeError{Msg: "provider " + string(provErr.Category) + " error: retry with backoff (" + provErr.Message + ")", Err: provErr}
		case provider.ErrCategoryBadRequest:
			return &RuntimeError{Msg: "bad request: validate request parameters (" + provErr.Message + ")", Err: provErr}
		}
	}
	return &RuntimeError{Msg: "provider call failed", Err: err}
}
